

# Making a complementary DNA
test_dna='ATGCCT'
#Homo sapiens Kidd blood group protein (SLC14A1) gene, exons 4, 5 and partial cds

dna='''ATGGAGGACAGCCCCACTATGGTTAGAGTGGACAGCCCCACTATGGTTAGGGGTGAAAACCAGGTTTCGCCATGTCAAGGGAGAAGGTGCTTCCCCAAAGCTCTTGGCTATGTCACCGGTGACATGAAAAAACTTGCCAACCAGCTTAAAGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNACAAACCCGTGGTGCTCCAGTTCATTGACTGGATTCTCCGGGGCATATCCCAAGTGGTGTTCGTCAACGACCCCGTCAGTGGAATCCTGATTCTGGTAGGACTTCTTGTTCAGAACCCCTGGTGGGCTCTCACTGGCTGGCTGGGAACAGTGGTCTCCACTCTGATGGCCCTCTTGCTCAGCCAGGACAG
'''
complementary_map=dna.maketrans('ATGC', 'TACG')
complementary_rna=dna.translate(complementary_map)
complementary_dna=dna.translate(complementary_map)[::-1]
print("Original Dna Sequence is\n5'....",dna, "....3'")
print("Complementary RNA Sequence is\n3'....",complementary_rna, "....5'")
print("Complementary Dna Sequence is\n3'....",complementary_dna, "....5'")
